#!/usr/bin/env python3
"""Build the checked-in Simplified Chinese catalog from reviewed mappings."""

from __future__ import annotations

import json
import re
from pathlib import Path

from check_translations import slint_messages


TRANSLATIONS = {
    "1 character": "1 个字符",
    "100-200 percent": "100%-200%",
    "100-50,000 retained lines": "保留 100-50,000 行",
    "120-260 px": "120-260 像素",
    "180-420 px when sessions are available": "存在会话时为 180-420 像素",
    "2 characters": "2 个字符",
    "10-300 columns, 3-100 rows": "10-300 列，3-100 行",
    "3 characters": "3 个字符",
    "4 characters": "4 个字符",
    "9-32 px": "9-32 像素",
    "A focused terminal workspace for SSH, Telnet, serial, and local shell sessions.": "专注于 SSH、Telnet、串口和本地 Shell 会话的终端工作区。",
    "APPLICATION": "应用",
    "APPLICATION THEME": "应用主题",
    "APPLICATION TYPOGRAPHY": "应用字体",
    "Automatic": "自动",
    "About": "关于",
    "Auto upload": "自动上传",
    "About AxSSH": "关于 AxSSH",
    "Accent / focus": "强调色 / 焦点",
    "Allow local connections without X authority": "允许无 X authority 的本地连接",
    "Appearance": "外观",
    "Application color palette": "应用配色方案",
    "Application command": "应用命令",
    "Application display mode": "应用显示模式",
    "Application font family": "应用字体系列",
    "Application interface font": "应用界面字体",
    "Apply one color family to both display modes": "为两种显示模式应用同一配色系列",
    "Async runtime": "异步运行时",
    "Authentication": "身份验证",
    "Authentication method": "身份验证方式",
    "BUFFER": "缓冲区",
    "Back": "后退",
    "Background": "背景",
    "Baud rate": "波特率",
    "Border": "边框",
    "Bright colors for bold text": "粗体文字使用亮色",
    "Bug reports": "问题报告",
    "COMPATIBILITY": "兼容性",
    "CONTENT AND STATES": "内容和状态",
    "CUSTOM DARK PALETTE": "自定义深色配色",
    "CUSTOM LIGHT PALETTE": "自定义浅色配色",
    "Cancel": "取消",
    "Cancel {0}": "取消 {0}",
    "Cancel selected": "取消所选",
    "Choose 1-4 characters or show the full group name": "选择 1-4 个字符或显示完整组名",
    "Choose Custom to launch this path without a command shell": "选择“自定义”以直接启动此路径，不经过命令 Shell",
    "Choose how this connection appears in the workspace.": "选择此连接在工作区中的显示方式。",
    "Choose system, light, or dark appearance": "选择跟随系统、浅色或深色外观",
    "Choose the remote and local directories opened by new SFTP tabs.": "选择新建 SFTP 标签页打开的远端和本地目录。",
    "Changes take effect after restarting AxSSH": "重启 AxSSH 后生效",
    "Clear": "清除",
    "Clear settings search": "清除设置搜索",
    "Close Current Tab": "关闭当前标签页",
    "Close tab": "关闭标签页",
    "Close terminal pane": "关闭终端窗格",
    "Collapse session sidebar": "收起会话侧栏",
    "Collapse {0} group": "收起 {0} 组",
    "Collapsed group label": "折叠组标签",
    "Collapsed group label length": "折叠组标签长度",
    "Color palette": "配色方案",
    "Connect": "连接",
    "Connect to {0}": "连接到 {0}",
    "Connection protocol": "连接协议",
    "Copy": "复制",
    "Copy Terminal Selection": "复制终端选区",
    "Copy Terminal Selection shortcut": "复制终端选区快捷键",
    "Copy a selection; otherwise paste": "有选区时复制，否则粘贴",
    "Copy current path": "复制当前路径",
    "Copy diagnostics": "复制诊断信息",
    "Copy selection on select": "选中后复制",
    "Local selection priority": "本地选区优先",
    "On: Alt/Option sends mouse gestures; off: standard xterm with Shift selection": "开启：Alt/Option 转发鼠标手势；关闭：标准 xterm，Shift 本地选择",
    "Copy version and build information without connection data": "复制不含连接数据的版本和构建信息",
    "Credential storage": "凭据存储",
    "Credential vault password": "凭据保险库密码",
    "Credentials used for this SSH connection.": "此 SSH 连接使用的凭据。",
    "Custom": "自定义",
    "Custom executable": "自定义可执行文件",
    "Cut": "剪切",
    "DISPLAY": "显示",
    "DEFAULTS": "默认值",
    "Danger": "危险",
    "Dark": "深色",
    "Data bits": "数据位",
    "Default terminal background color": "默认终端背景色",
    "Default terminal columns": "默认终端列数",
    "Default terminal rows": "默认终端行数",
    "Default terminal size": "默认终端尺寸",
    "Default terminal text color": "默认终端文字颜色",
    "Delete": "删除",
    "Download": "下载",
    "Delete group": "删除组",
    "Delete server": "删除服务器",
    "Delete {0} and its saved credential?": "删除 {0} 及其已保存的凭据？",
    "Delete {0}? Servers in this group will move to Ungrouped.": "删除 {0}？该组中的服务器将移至“未分组”。",
    "Detected key": "检测到的密钥",
    "Detected locations": "检测到的位置",
    "Detected private keys": "检测到的私钥",
    "Detected serial ports": "检测到的串口",
    "Diagnostics": "诊断信息",
    "Dialog and transient overlay tint": "对话框和临时遮罩色",
    "Display mode": "显示模式",
    "Dividers and control outlines": "分隔线和控件轮廓",
    "Edit": "编辑",
    "Edit selected remote file": "编辑选中的远端文件",
    "Remote text editor": "远端文本编辑器",
    "RENDERING": "渲染",
    "Renderer": "渲染器",
    "Rendering backend": "渲染后端",
    "Compact terminal rendering": "紧凑终端渲染",
    "Reduce terminal items and omit default background rectangles": "减少终端绘制项并省略默认背景矩形",
    "Cache unchanged terminal rows": "缓存未变化的终端行",
    "Reuse GPU row layers; may increase graphics memory": "复用 GPU 行图层；可能增加图形内存",
    "Monitoring": "监控中",
    "Remote changed": "远端已更改",
    "Rename": "重命名",
    "Rename selected remote entry": "重命名选中的远端条目",
    "Save As remote path": "另存为远端路径",
    "Upload": "上传",
    "Upload selected local files": "上传选中的本地文件",
    "Enable SSH X11 forwarding": "启用 SSH X11 转发",
    "Endpoint": "端点",
    "Enable semantic highlighting": "启用语义高亮",
    "Enter #RRGGBB or #RRGGBBAA values. Unsafe contrast falls back to readable colors when saved.": "输入 #RRGGBB 或 #RRGGBBAA。保存时，对比度不足的颜色会回退为可读颜色。",
    "Enter the Telnet server address.": "输入 Telnet 服务器地址。",
    "Enter the host address and SSH account.": "输入主机地址和 SSH 账户。",
    "Encrypted application vault": "应用加密保险库",
    "Error": "错误",
    "Error and destructive indicators": "错误和破坏性操作指示",
    "Errors and HTTP 5xx": "错误和 HTTP 5xx",
    "Executable path": "可执行文件路径",
    "Executable used for new local terminal tabs": "新建本地终端标签页使用的可执行文件",
    "Existing session groups": "现有会话组",
    "Expand session sidebar": "展开会话侧栏",
    "Expand {0} group": "展开 {0} 组",
    "Export Selected": "导出所选项",
    "Export Selected shortcut": "导出所选项快捷键",
    "Export Selected to Clipboard": "将所选项导出到剪贴板",
    "File": "文件",
    "File transfers": "文件传输",
    "Failed ({0})": "失败 ({0})",
    "Files and transfers area sizes": "文件和传输区域大小",
    "Flow control": "流控制",
    "Focus rings, selection, and active indicators": "焦点环、选择和活动状态指示",
    "Focused refresh rate": "聚焦刷新率",
    "Focused terminal refresh rate": "聚焦终端刷新率",
    "Terminal updates while the pane is focused": "终端窗格聚焦时的刷新帧率",
    "Unfocused refresh rate": "非聚焦刷新率",
    "Unfocused terminal refresh rate": "非聚焦终端刷新率",
    "Visible terminal updates while another pane is focused": "其他窗格聚焦时可见终端的刷新帧率",
    "Follow system": "跟随系统",
    "Font family": "字体系列",
    "Font size": "字体大小",
    "Foreground": "前景",
    "Forward": "前进",
    "Forward X11 applications": "转发 X11 应用",
    "Full name": "完整名称",
    "General": "通用",
    "GPU": "GPU",
    "Group": "组",
    "Group name": "组名",
    "Help": "帮助",
    "Highlight statuses and log levels": "高亮状态和日志级别",
    "Hidden": "隐藏",
    "Host": "主机",
    "Hover and secondary surfaces": "悬停和次级表面",
    "Identity": "标识",
    "Import from Clipboard": "从剪贴板导入",
    "Import from Clipboard shortcut": "从剪贴板导入快捷键",
    "Information": "信息",
    "Informational status words": "信息状态词",
    "INTERFACE": "界面",
    "Interface": "界面",
    "Interface language": "界面语言",
    "KEYBOARD": "键盘",
    "Keyboard Shortcuts": "键盘快捷键",
    "LAYOUT": "布局",
    "LOCAL X SERVER": "本地 X SERVER",
    "Launch the selected X server only when a forwarded graphical app opens": "仅在转发的图形应用打开时启动所选 X server",
    "Language": "语言",
    "Language used by the AxSSH interface": "AxSSH 界面使用的语言",
    "Leave blank to keep saved password": "留空以保留已保存的密码",
    "License": "许可证",
    "Light": "浅色",
    "Line height": "行高",
    "Loading": "正在加载",
    "Loading...": "正在加载...",
    "Local Shell": "本地 Shell",
    "Local shell": "本地 Shell",
    "Local X server application path": "本地 X server 应用路径",
    "Local X server provider": "本地 X server 提供程序",
    "Local default directory": "本地默认目录",
    "Local files": "本地文件",
    "Loopback only; required by MacXServer and -ac Windows servers": "仅限回环地址；MacXServer 和使用 -ac 的 Windows server 需要此项",
    "MOUSE": "鼠标",
    "Masks usernames and the middle IPv4 octets in the session sidebar": "在会话侧栏中遮盖用户名和 IPv4 地址的中间字段",
    "Modified": "修改时间",
    "More": "更多",
    "Move Current Workspace to New Window": "将当前工作区移至新窗口",
    "Move workspace to new window": "将工作区移至新窗口",
    "Muted text": "弱化文字",
    "Name": "名称",
    "Navigation and title surfaces": "导航和标题表面",
    "New Local Shell": "新建本地 Shell",
    "New Server": "新建服务器",
    "New Server shortcut": "新建服务器快捷键",
    "New group": "新建组",
    "New name": "新名称",
    "Next Tab": "下一个标签页",
    "No files": "没有文件",
    "No known local X server was found": "未找到已知的本地 X server",
    "No saved connections": "没有已保存的连接",
    "No saved servers": "没有已保存的服务器",
    "No settings match this search.": "没有与此搜索匹配的设置。",
    "No failed transfers": "没有失败的传输",
    "No successful transfers": "没有成功的传输",
    "No transfers in progress": "没有正在传输的文件",
    "Open": "打开",
    "Open Settings": "打开设置",
    "Open Settings shortcut": "打开设置快捷键",
    "Open a new local shell tab": "打开新的本地 Shell 标签页",
    "Open a saved session or create a new tab.": "打开已保存的会话或新建标签页。",
    "Open local shell": "打开本地 Shell",
    "Open log folder": "打开日志文件夹",
    "Open saved connection": "打开已保存的连接",
    "Open the AxSSH issue tracker": "打开 AxSSH 问题跟踪器",
    "Option acts as Meta": "Option 作为 Meta",
    "Optional": "可选",
    "Optional; empty saves in system credential store": "可选；留空时保存到系统凭据存储",
    "Optional; enter only when connecting or saving": "可选；仅在连接或保存时输入",
    "Overlay": "遮罩",
    "Pane": "窗格",
    "Panel": "面板",
    "Panel alternative": "次级面板",
    "Parity": "校验位",
    "Password": "密码",
    "Password authentication": "密码验证",
    "Pause": "暂停",
    "Pause {0}": "暂停 {0}",
    "Pause selected": "暂停所选",
    "Paste": "粘贴",
    "Paste Into Terminal": "粘贴到终端",
    "Paste Into Terminal shortcut": "粘贴到终端快捷键",
    "Path": "路径",
    "Platform home directory": "平台主目录",
    "Port": "端口",
    "Positive status indicators": "成功状态指示",
    "Previous Tab": "上一个标签页",
    "Primary readable text": "主要可读文字",
    "Primary workspace surface": "主要工作区表面",
    "Private key": "私钥",
    "Private key authentication": "私钥验证",
    "Private key passphrase": "私钥口令",
    "Private key passphrase (optional)": "私钥口令（可选）",
    "Private key path": "私钥路径",
    "Production server": "生产服务器",
    "Protocol": "协议",
    "Provider": "提供程序",
    "Refresh": "刷新",
    "Refresh serial ports": "刷新串口",
    "Resume": "继续",
    "Resume {0}": "继续 {0}",
    "Resume selected": "继续所选",
    "Remote and local file pane sizes": "远端和本地文件窗格大小",
    "Remote default directory": "远端默认目录",
    "Remote files": "远端文件",
    "Remembered password storage": "已记住密码的存储位置",
    "Rename group": "重命名组",
    "Report a bug": "报告问题",
    "Reset defaults": "恢复默认值",
    "Return Workspace to Main Window": "将工作区返回主窗口",
    "Return workspace to main window": "将工作区返回主窗口",
    "Review before sharing": "分享前请检查内容",
    "Right-click always pastes": "右键始终粘贴",
    "Right-click copy or paste": "右键复制或粘贴",
    "Runtime logs": "运行日志",
    "SEMANTIC HIGHLIGHTING": "语义高亮",
    "SFTP directories": "SFTP 目录",
    "SFTP files": "SFTP 文件",
    "SFTP local default directory": "SFTP 本地默认目录",
    "SFTP remote default directory": "SFTP 远端默认目录",
    "SHA-256 fingerprint": "SHA-256 指纹",
    "SSH agent": "SSH agent",
    "SSH authentication method": "SSH 身份验证方式",
    "SSH host key changed": "SSH 主机密钥已更改",
    "SSH host key revoked": "SSH 主机密钥已撤销",
    "SSH password": "SSH 密码",
    "SSH transport": "SSH 传输",
    "SSH username": "SSH 用户名",
    "SUPPORT": "支持",
    "SURFACES": "表面",
    "Save": "保存",
    "Save & connect": "保存并连接",
    "Save SSH password for future connections": "保存 SSH 密码供以后连接使用",
    "Save password (optional)": "保存密码（可选）",
    "Save password in": "密码保存位置",
    "Save session": "保存会话",
    "Saved connections": "已保存的连接",
    "Scrollback": "回滚行数",
    "Search all settings": "搜索所有设置",
    "Search results": "搜索结果",
    "Search settings": "搜索设置",
    "Secondary labels and metadata": "次级标签和元数据",
    "Select All": "全选",
    "Select a detected device or enter its port name manually.": "选择检测到的设备，或手动输入端口名称。",
    "Select all files": "选择所有文件",
    "Select the transport used by this saved connection.": "选择此已保存连接使用的传输方式。",
    "Select {0}": "选择 {0}",
    "Selection": "选择",
    "Send Option+key as an Escape-prefixed Meta key": "将 Option+按键作为带 Escape 前缀的 Meta 键发送",
    "Serial": "串口",
    "Serial baud rate": "串口波特率",
    "Serial data bits": "串口数据位",
    "Serial flow control": "串口流控制",
    "Serial parity": "串口校验位",
    "Serial port": "串口",
    "Serial port name": "串口名称",
    "Serial stop bits": "串口停止位",
    "Serial transport": "串口传输",
    "Session group": "会话组",
    "Session mask character": "会话掩码字符",
    "Session name": "会话名称",
    "Session sidebar width": "会话侧栏宽度",
    "Session transfer command": "会话传输命令",
    "Sessions": "会话",
    "Settings": "设置",
    "Settings...": "设置...",
    "Shortcuts": "快捷键",
    "Size": "大小",
    "Speed": "速度",
    "Split active terminal horizontally": "水平拆分当前终端",
    "Split active terminal vertically": "垂直拆分当前终端",
    "Split horizontally (Alt+Shift+J)": "水平拆分（Alt+Shift+J）",
    "Split vertically (Alt+Shift+L)": "垂直拆分（Alt+Shift+L）",
    "Start for first X11 application": "首个 X11 应用打开时启动",
    "Status": "状态",
    "Stop bits": "停止位",
    "Success": "成功",
    "Success ({0})": "成功 ({0})",
    "Successful status words and HTTP 2xx": "成功状态词和 HTTP 2xx",
    "System credential store": "系统凭据存储",
    "Software": "软件",
    "Switch SSH/SFTP Tab": "切换 SSH/SFTP 标签页",
    "Switch SSH/SFTP Tab shortcut": "切换 SSH/SFTP 标签页快捷键",
    "TERMINAL": "终端",
    "TERMINAL DEFAULTS": "终端默认设置",
    "TYPOGRAPHY": "字体",
    "Telnet protocol": "Telnet 协议",
    "Telnet sends terminal traffic without encryption or host identity verification.": "Telnet 传输终端流量时不加密，也不验证主机身份。",
    "Terminal": "终端",
    "Terminal character-cell font": "终端字符单元格字体",
    "Terminal command": "终端命令",
    "Terminal error highlight color": "终端错误高亮颜色",
    "Terminal font family": "终端字体系列",
    "Terminal font size": "终端字体大小",
    "Terminal information highlight color": "终端信息高亮颜色",
    "Terminal line height percentage": "终端行高百分比",
    "Terminal pane heights": "终端窗格高度",
    "Terminal pane widths": "终端窗格宽度",
    "Terminal scrollback lines": "终端回滚行数",
    "Terminal success highlight color": "终端成功高亮颜色",
    "Terminal text brightness": "终端文字亮度",
    "Terminal text selection background": "终端文字选择背景",
    "Terminal warning highlight color": "终端警告高亮颜色",
    "Text": "文字",
    "Text brightness": "文字亮度",
    "Theme default": "主题默认值",
    "Toggle Session Sidebar": "切换会话侧栏",
    "Toggle Session Sidebar shortcut": "切换会话侧栏快捷键",
    "Transferring ({0})": "传输中 ({0})",
    "Trust and continue": "信任并继续",
    "Trust new key": "信任新密钥",
    "Remove revoked record": "移除已撤销记录",
    "Unknown SSH host key": "未知 SSH 主机密钥",
    "Unlock encrypted credentials": "解锁加密凭据",
    "Update session": "更新会话",
    "Use the bright ANSI palette for bold text": "为粗体文字使用明亮 ANSI 调色板",
    "60-120 percent; 100 percent preserves terminal colors": "60%-120%；100% 保留终端原色",
    "Used for remembered passwords and new passwords entered in the session editor": "用于已记住的密码和在会话编辑器中新输入的密码",
    "Username": "用户名",
    "Vault password": "保险库密码",
    "Version {0}": "版本 {0}",
    "View": "视图",
    "WORKSPACE": "工作区",
    "Warning": "警告",
    "Warnings and HTTP 4xx": "警告和 HTTP 4xx",
    "Window": "窗口",
    "Workspace": "工作区",
    "Workspace command": "工作区命令",
    "Workspace tab width": "工作区标签页宽度",
    "X server used by forwarded graphical applications": "转发图形应用使用的 X server",
    "lines": "行",
    "px": "像素",
    "{0} accent color": "{0} 强调色",
    "{0} background color": "{0} 背景色",
    "{0} border color": "{0} 边框色",
    "{0} danger color": "{0} 危险色",
    "{0} muted text color": "{0} 弱化文字颜色",
    "{0} overlay color": "{0} 遮罩色",
    "{0} panel color": "{0} 面板颜色",
    "{0} secondary panel color": "{0} 次级面板颜色",
    "{0} success color": "{0} 成功色",
    "{0} terminal background color": "{0} 终端背景色",
    "{0} terminal foreground color": "{0} 终端前景色",
    "{0} terminal selection color": "{0} 终端选择颜色",
    "{0} text color": "{0} 文字颜色",
}

UNCHANGED = {
    "%", "+", "<", ">", ">_", "115200", "22", "AxSSH", "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
    "root", "server.example.com", "x", "FPS", "{0}: {1}", "~", "~/.ssh/id_ed25519",
    "/dev/cu.usbserial or COM3", "English", "Simplified Chinese", "SSH", "SFTP", "SLINT", "Telnet", "X11",
}


def po_quote(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def placeholders(value: str) -> set[str]:
    return set(re.findall(r"\{\d+\}", value))


def main() -> int:
    root = Path(__file__).resolve().parents[1]
    messages = slint_messages(root / "ui")
    unknown = sorted(messages - TRANSLATIONS.keys() - UNCHANGED)
    stale = sorted(TRANSLATIONS.keys() - messages)
    if unknown or stale:
        if unknown:
            print("Unmapped messages:")
            print("\n".join(f"  {message}" for message in unknown))
        if stale:
            print("Stale mappings:")
            print("\n".join(f"  {message}" for message in stale))
        return 1

    lines = [
        'msgid ""',
        'msgstr ""',
        '"Project-Id-Version: AxSSH 2026.8.12\\n"',
        '"Language: zh_CN\\n"',
        '"PO-Revision-Date: 2026-08-12 17:31+0800\\n"',
        '"Last-Translator: AxSSH maintainers\\n"',
        '"Language-Team: Simplified Chinese\\n"',
        '"MIME-Version: 1.0\\n"',
        '"Content-Type: text/plain; charset=UTF-8\\n"',
        '"Content-Transfer-Encoding: 8bit\\n"',
        '"Plural-Forms: nplurals=1; plural=0;\\n"',
        "",
    ]
    for message in sorted(messages):
        translated = TRANSLATIONS.get(message, message)
        if placeholders(message) != placeholders(translated):
            raise ValueError(f"placeholder mismatch for {message!r}")
        lines.extend((f"msgid {po_quote(message)}", f"msgstr {po_quote(translated)}", ""))
    output = root / "translations/zh-CN/LC_MESSAGES/ax_ssh.po"
    output.write_text("\n".join(lines), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
